# Generated by Django 3.1.4 on 2021-01-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewcount',
            field=models.IntegerField(default=0),
        ),
    ]
