# Generated by Django 3.1.4 on 2021-01-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210101_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('music', 'Music'), ('travel', 'Travel'), ('photography', 'Photography'), ('fashion', 'Fashion'), ('automobile', 'Automobile'), ('design', 'Design'), ('movie', 'Movie'), ('history', 'History'), ('education', 'Education'), ('lifestyle', 'Lifestyle')], default='general', max_length=120, verbose_name='Category'),
        ),
    ]
