# Generated by Django 3.1.4 on 2020-12-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201228_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
